# Generated by Django 4.1.7 on 2023-06-23 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='eh_supervisor',
            field=models.BooleanField(default=False),
        ),
    ]
