# Generated by Django 4.1.7 on 2023-06-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_eh_supervisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
