# Generated by Django 4.1.7 on 2023-09-21 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuario_fone_alter_usuario_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='eh_funcionario',
            field=models.BooleanField(default=False),
        ),
    ]
