# Generated by Django 4.1.7 on 2023-05-30 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True)),
                ('atualizado', models.DateField(auto_now=True)),
                ('ativa', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contribuintes',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='empbase.base')),
                ('nome', models.CharField(max_length=200)),
            ],
            bases=('empbase.base',),
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='empbase.base')),
                ('cod', models.IntegerField(primary_key=True, serialize=False)),
                ('cnpj', models.CharField(max_length=30, unique=True)),
                ('inscest', models.CharField(blank=True, max_length=30, null=True)),
                ('inscmun', models.CharField(blank=True, max_length=30, null=True)),
                ('inscjunta', models.CharField(blank=True, max_length=30, null=True)),
                ('apelido', models.CharField(max_length=100)),
                ('nome', models.CharField(max_length=100)),
                ('rsocial', models.CharField(max_length=100)),
                ('natjuridica', models.CharField(max_length=100)),
                ('inicio', models.DateField()),
                ('tipoend', models.CharField(max_length=30)),
                ('endereco', models.CharField(max_length=150)),
                ('num', models.CharField(max_length=30)),
                ('bairro', models.CharField(max_length=100)),
                ('municipio', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=10)),
                ('pais', models.CharField(max_length=50)),
                ('cep', models.CharField(max_length=10)),
                ('cnae', models.CharField(max_length=15)),
                ('capital', models.FloatField()),
                ('email', models.CharField(max_length=100)),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='empbase.contribuintes')),
            ],
            bases=('empbase.base',),
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='empbase.base')),
                ('cod', models.IntegerField()),
                ('nome', models.CharField(max_length=150)),
                ('cpf', models.CharField(max_length=14)),
                ('pis', models.CharField(max_length=14)),
                ('admissao', models.DateField()),
                ('salario', models.FloatField(blank=True, null=True)),
                ('cargo', models.CharField(max_length=30)),
                ('cbo', models.CharField(max_length=8)),
                ('rg', models.CharField(blank=True, max_length=15, null=True)),
                ('rgemiss', models.DateField(blank=True, max_length=5, null=True)),
                ('rgorgao', models.CharField(blank=True, max_length=5, null=True)),
                ('ctps', models.CharField(max_length=10)),
                ('ctpsserie', models.CharField(max_length=5)),
                ('ctpsdata', models.DateField(blank=True, null=True)),
                ('ctpsuf', models.CharField(max_length=2)),
                ('turno', models.CharField(max_length=30)),
                ('logradouro', models.CharField(max_length=100)),
                ('num', models.CharField(max_length=10)),
                ('bairro', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=70)),
                ('uf', models.CharField(max_length=2)),
                ('cep', models.IntegerField()),
                ('datanasc', models.DateField()),
                ('cidadenasc', models.CharField(max_length=100)),
                ('ufnasc', models.CharField(max_length=2)),
                ('genero', models.CharField(max_length=15)),
                ('pai', models.CharField(blank=True, max_length=100, null=True)),
                ('mae', models.CharField(max_length=100)),
                ('demissao', models.DateField(blank=True, null=True)),
                ('demitido', models.BooleanField()),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='empbase.empresa')),
            ],
            bases=('empbase.base',),
        ),
        migrations.CreateModel(
            name='UltimoAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp', models.DateField()),
                ('atualizado', models.DateField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='empbase.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='TemAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atualizado', models.DateField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('emp', models.ManyToManyField(to='empbase.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Rescisao',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='empbase.base')),
                ('tipo', models.CharField(choices=[('1', 'Pedido Trabalhado'), ('2', 'Pedido Indenizado'), ('3', 'Dispensa Indenizada'), ('4', 'Dispensa Trabalhada'), ('5', 'Término Experiência'), ('6', 'Término Antecipado'), ('7', 'Término Antecipado Empregado'), ('8', 'Justa Causa')], max_length=2)),
                ('aviso', models.DateField(blank=True, null=True)),
                ('inicio', models.DateField()),
                ('final', models.DateField()),
                ('func', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='empbase.funcionario')),
            ],
            bases=('empbase.base',),
        ),
        migrations.CreateModel(
            name='Obras',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='empbase.base')),
                ('cod', models.CharField(blank=True, max_length=30, null=True)),
                ('cnpj', models.CharField(blank=True, max_length=30, null=True)),
                ('cei', models.CharField(blank=True, max_length=30, null=True)),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=150)),
                ('num', models.CharField(max_length=30)),
                ('bairro', models.CharField(max_length=100)),
                ('municipio', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=10)),
                ('cep', models.CharField(blank=True, max_length=10, null=True)),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='empbase.empresa')),
            ],
            bases=('empbase.base',),
        ),
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='empbase.base')),
                ('numero', models.IntegerField()),
                ('canc', models.IntegerField()),
                ('comp', models.DateField()),
                ('valor', models.FloatField()),
                ('inss', models.FloatField()),
                ('iss', models.FloatField()),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='empbase.empresa')),
                ('tomador', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='empbase.obras')),
            ],
            bases=('empbase.base',),
        ),
        migrations.CreateModel(
            name='Ferias',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='empbase.base')),
                ('aviso', models.DateField(blank=True, null=True)),
                ('inicio', models.DateField()),
                ('final', models.DateField()),
                ('func', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='empbase.funcionario')),
            ],
            bases=('empbase.base',),
        ),
        migrations.CreateModel(
            name='Alocacao',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='empbase.base')),
                ('comp', models.DateField()),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='empbase.empresa')),
                ('func', models.ManyToManyField(to='empbase.funcionario')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='empbase.obras')),
            ],
            bases=('empbase.base',),
        ),
    ]
