# Generated by Django 4.2 on 2023-05-31 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empbase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obras',
            name='cod',
            field=models.IntegerField(blank=True, max_length=30, null=True),
        ),
    ]
