# Generated by Django 4.2 on 2023-10-25 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empbase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='diafolga',
            field=models.IntegerField(default=0),
        ),
    ]
