# Generated by Django 4.2 on 2023-06-01 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empbase', '0002_alter_obras_cod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obras',
            name='cod',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
