# Generated by Django 4.2 on 2023-06-01 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empbase', '0003_alter_obras_cod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obras',
            name='cod',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
