# Generated by Django 4.2 on 2023-06-01 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empbase', '0004_alter_obras_cod'),
    ]

    operations = [
        migrations.AddField(
            model_name='alocacao',
            name='nota',
            field=models.ForeignKey(default=1210, on_delete=django.db.models.deletion.DO_NOTHING, to='empbase.notas'),
            preserve_default=False,
        ),
    ]
