# Generated by Django 4.2 on 2023-10-25 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empbase', '0004_holerite_emp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValeTransporte',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='empbase.base')),
                ('nome', models.CharField(blank=True, default='Hortolândia', max_length=100, null=True)),
                ('valor', models.FloatField(blank=True, default=5.25, null=True)),
                ('emp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='empbase.empresa')),
            ],
            bases=('empbase.base',),
        ),
    ]
