# Generated by Django 4.2 on 2023-06-01 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empbase', '0005_alocacao_nota'),
    ]

    operations = [
        migrations.RenameField(
            model_name='obras',
            old_name='cei',
            new_name='cno',
        ),
        migrations.AlterField(
            model_name='alocacao',
            name='nota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='empbase.notas'),
        ),
    ]
