# Generated by Django 4.2 on 2023-10-25 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empbase', '0006_funcionario_vt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valetransporte',
            name='nome',
            field=models.CharField(default='Hortolândia', max_length=100),
        ),
        migrations.AlterField(
            model_name='valetransporte',
            name='valor',
            field=models.FloatField(default=5.25),
        ),
    ]
