# Generated by Django 4.1.7 on 2023-06-12 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empbase', '0006_rename_cei_obras_cno_alter_alocacao_nota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alocacao',
            name='nota',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='empbase.notas'),
        ),
        migrations.AlterField(
            model_name='alocacao',
            name='obra',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='empbase.obras'),
        ),
    ]
