# Generated by Django 4.2 on 2023-10-25 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empbase', '0007_alter_valetransporte_nome_alter_valetransporte_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='paga_vr',
            field=models.BooleanField(default=False),
        ),
    ]
