# Generated by Django 4.2 on 2023-06-12 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empbase', '0007_alter_alocacao_nota_alter_alocacao_obra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escritorio',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='empbase.base')),
                ('cnpj', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('inscest', models.CharField(blank=True, max_length=30, null=True)),
                ('inscmun', models.CharField(blank=True, max_length=30, null=True)),
                ('inscjunta', models.CharField(blank=True, max_length=30, null=True)),
                ('apelido', models.CharField(max_length=100)),
                ('nome', models.CharField(max_length=100)),
                ('rsocial', models.CharField(max_length=100)),
                ('natjuridica', models.CharField(blank=True, max_length=100, null=True)),
                ('inicio', models.DateField(blank=True, null=True)),
                ('tipoend', models.CharField(blank=True, max_length=30, null=True)),
                ('endereco', models.CharField(blank=True, max_length=150, null=True)),
                ('num', models.CharField(blank=True, max_length=30, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('municipio', models.CharField(blank=True, max_length=100, null=True)),
                ('uf', models.CharField(blank=True, max_length=10, null=True)),
                ('pais', models.CharField(blank=True, max_length=50, null=True)),
                ('cep', models.CharField(blank=True, max_length=10, null=True)),
                ('cnae', models.CharField(blank=True, max_length=15, null=True)),
                ('capital', models.FloatField(blank=True, null=True)),
                ('email', models.CharField(max_length=100)),
            ],
            bases=('empbase.base',),
        ),
        migrations.CreateModel(
            name='Imposto',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='empbase.base')),
                ('nome', models.CharField(max_length=80)),
                ('valor', models.FloatField()),
                ('comp', models.DateField()),
                ('vcto', models.DateField(blank=True, null=True)),
                ('enviado', models.BooleanField(default=False)),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='empbase.empresa')),
            ],
            bases=('empbase.base',),
        ),
    ]
