# Generated by Django 4.2 on 2023-06-12 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empbase', '0008_escritorio_imposto'),
    ]

    operations = [
        migrations.AddField(
            model_name='temacesso',
            name='escr',
            field=models.ManyToManyField(to='empbase.escritorio'),
        ),
    ]
