# Generated by Django 4.1.7 on 2023-10-26 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empbase', '0008_empresa_paga_vr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubrica',
            name='cod',
            field=models.IntegerField(),
        ),
    ]
