# Generated by Django 4.2 on 2023-06-12 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empbase', '0009_temacesso_escr'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='escr',
            field=models.ForeignKey(default=2747, on_delete=django.db.models.deletion.DO_NOTHING, to='empbase.escritorio'),
            preserve_default=False,
        ),
    ]
