# Generated by Django 4.1.7 on 2023-10-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empbase', '0009_alter_rubrica_cod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='diafolga',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
