# Generated by Django 4.1.7 on 2023-10-26 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empbase', '0010_alter_turno_diafolga'),
    ]

    operations = [
        migrations.AddField(
            model_name='diadetrabalho',
            name='horastrabalhadas',
            field=models.IntegerField(default=0),
        ),
    ]
