# Generated by Django 4.1.7 on 2023-10-26 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empbase', '0011_diadetrabalho_horastrabalhadas'),
    ]

    operations = [
        migrations.AddField(
            model_name='diadetrabalho',
            name='retificar',
            field=models.BooleanField(default=False),
        ),
    ]
