# Generated by Django 4.1.7 on 2023-06-16 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empbase', '0012_alter_holerite_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='situacao',
            field=models.CharField(default='Ativa', max_length=20),
        ),
    ]
