# Generated by Django 4.1.7 on 2023-06-16 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empbase', '0014_holerite_funcs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='empbase.base')),
                ('pago', models.BooleanField(default=False)),
                ('func', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='empbase.funcionario')),
            ],
            bases=('empbase.base',),
        ),
        migrations.AlterField(
            model_name='holerite',
            name='funcs',
            field=models.ManyToManyField(to='empbase.pagamento'),
        ),
    ]
