# Generated by Django 4.1.7 on 2023-06-23 12:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('empbase', '0016_imposto_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='escritorio',
            name='responsavel',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
