# Generated by Django 4.1.7 on 2023-06-23 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empbase', '0017_escritorio_responsavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='ultimoacesso',
            name='escr',
            field=models.ForeignKey(default=4682, on_delete=django.db.models.deletion.DO_NOTHING, to='empbase.escritorio'),
            preserve_default=False,
        ),
    ]
