# Generated by Django 4.1.7 on 2023-06-23 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empbase', '0018_ultimoacesso_escr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='escritorio',
            old_name='responsavel',
            new_name='usuarios',
        ),
    ]
