# Generated by Django 4.1.7 on 2023-06-28 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empbase', '0019_rename_responsavel_escritorio_usuarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alocacao',
            name='obra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='empbase.obras'),
        ),
    ]
