# Generated by Django 4.1.7 on 2023-06-30 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empbase', '0020_alter_alocacao_obra'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='exonera_folha',
            field=models.BooleanField(default=False),
        ),
    ]
