# Generated by Django 4.1.7 on 2023-07-10 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empbase', '0021_empresa_exonera_folha'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='formaenvio',
            field=models.CharField(default='2', max_length=5),
        ),
    ]
