# Generated by Django 4.1.7 on 2023-07-21 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empbase', '0022_empresa_formaenvio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rubrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cod', models.IntegerField(unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='ferias',
            name='func',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empbase.funcionario'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='turno',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='holerite',
            name='emp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empbase.empresa'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='func',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empbase.funcionario'),
        ),
        migrations.AlterField(
            model_name='rescisao',
            name='func',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empbase.funcionario'),
        ),
        migrations.CreateModel(
            name='Lancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comp', models.CharField(max_length=7)),
                ('func', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empbase.funcionario')),
                ('rub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empbase.rubrica')),
            ],
        ),
    ]
