# Generated by Django 4.1.7 on 2023-07-21 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empbase', '0024_turno_rename_turno_funcionario_turnoinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Turno',
        ),
    ]
