# Generated by Django 4.1.7 on 2023-07-21 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empbase', '0025_delete_turno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='empbase.base')),
                ('entrada', models.CharField(default='08:00', max_length=5)),
                ('intervalo', models.CharField(default='12:00', max_length=5)),
                ('fimintervalo', models.CharField(default='13:00', max_length=5)),
                ('saida', models.CharField(default='17:00', max_length=5)),
                ('entradafs', models.CharField(default='08:00', max_length=5)),
                ('intervalofs', models.CharField(blank=True, max_length=5, null=True)),
                ('fimintervalofs', models.CharField(blank=True, max_length=5, null=True)),
                ('saidafs', models.CharField(default='12:00', max_length=5)),
            ],
            bases=('empbase.base',),
        ),
    ]
