# Generated by Django 4.1.7 on 2023-07-21 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empbase', '0026_turno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='turnoinfo',
        ),
    ]
