# Generated by Django 4.1.7 on 2023-07-21 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empbase', '0027_remove_funcionario_turnoinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='jornada',
            field=models.ForeignKey(default=7352, on_delete=django.db.models.deletion.DO_NOTHING, to='empbase.turno'),
        ),
    ]
