# Generated by Django 4.1.7 on 2023-07-26 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empbase', '0028_funcionario_jornada'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiadeTrabalho',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='empbase.base')),
                ('dia', models.DateField()),
                ('entrada', models.CharField(default='00:00', max_length=5)),
                ('intervalo', models.CharField(default='00:00', max_length=5)),
                ('fimintervalo', models.CharField(default='00:00', max_length=5)),
                ('saida', models.CharField(default='00:00', max_length=5)),
                ('encerrado', models.BooleanField(default=False)),
                ('func', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empbase.funcionario')),
            ],
            bases=('empbase.base',),
        ),
    ]
