# Generated by Django 4.1.7 on 2023-07-27 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empbase', '0029_diadetrabalho'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diadetrabalho',
            old_name='dia',
            new_name='iniciodia',
        ),
        migrations.AlterField(
            model_name='diadetrabalho',
            name='entrada',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='diadetrabalho',
            name='fimintervalo',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='diadetrabalho',
            name='intervalo',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='diadetrabalho',
            name='saida',
            field=models.DateField(),
        ),
    ]
