# Generated by Django 4.1.7 on 2023-07-27 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empbase', '0030_rename_dia_diadetrabalho_iniciodia_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diadetrabalho',
            old_name='iniciodia',
            new_name='inicioem',
        ),
    ]
