# Generated by Django 4.1.7 on 2023-07-27 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empbase', '0031_rename_iniciodia_diadetrabalho_inicioem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diadetrabalho',
            name='entrada',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='diadetrabalho',
            name='fimintervalo',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='diadetrabalho',
            name='inicioem',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='diadetrabalho',
            name='intervalo',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='diadetrabalho',
            name='saida',
            field=models.DateTimeField(),
        ),
    ]
