# Generated by Django 4.1.7 on 2023-07-27 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empbase', '0032_alter_diadetrabalho_entrada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diadetrabalho',
            name='inicioem',
            field=models.DateField(),
        ),
    ]
