# Generated by Django 4.1.7 on 2023-07-28 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empbase', '0033_alter_diadetrabalho_inicioem'),
    ]

    operations = [
        migrations.AddField(
            model_name='diadetrabalho',
            name='entrou',
            field=models.BooleanField(default=False),
        ),
    ]
